# Generated by Django 5.1.4 on 2025-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_filtered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Кол-во упоминаний')),
            ],
            options={
                'db_table': 'skills_filtered',
            },
        ),
    ]
