# Generated by Django 5.1.4 on 2025-01-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('proportion', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Кол-во упоминаний')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('key_skills', models.CharField(max_length=512, verbose_name='Ключевые навыки')),
                ('salary_from', models.FloatField(verbose_name='Зарплата от')),
                ('salary_to', models.FloatField(verbose_name='Зарплата до')),
                ('salary_average', models.FloatField(verbose_name='Средняя зарплата')),
                ('salary_currency', models.CharField(max_length=64, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=64, verbose_name='Местоположение')),
                ('published_at', models.DateTimeField(verbose_name='Время публикации')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=64, verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('proportion', models.FloatField(verbose_name='Кол-во вакансий')),
            ],
            options={
                'db_table': 'years',
            },
        ),
    ]
