# Generated by Django 5.1.4 on 2025-01-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
