# Generated by Django 5.1.4 on 2025-01-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('key_skills', models.CharField(max_length=512, verbose_name='Ключевые навыки')),
                ('salary_from', models.FloatField(verbose_name='Зарплата от')),
                ('salary_to', models.FloatField(verbose_name='Зарплата до')),
                ('salary_average', models.FloatField(verbose_name='Средняя зарплата')),
                ('salary_currency', models.CharField(max_length=64, verbose_name='Валюта')),
                ('area_name', models.CharField(max_length=64, verbose_name='Местоположение')),
                ('published_at', models.DateTimeField(verbose_name='Время публикации')),
                ('date', models.IntegerField(verbose_name='Год публикации')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
    ]
