# Generated by Django 5.1.4 on 2025-01-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vacancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='area_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.IntegerField(null=True, verbose_name='Год публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='key_skills',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_currency',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Валюта'),
        ),
    ]
