# Generated by Django 5.1.4 on 2025-01-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacancy_area_name_alter_vacancy_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_filtered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('proportion', models.FloatField(verbose_name='Доля вакансий')),
            ],
            options={
                'db_table': 'cities_filtered',
            },
        ),
        migrations.CreateModel(
            name='Skill_filtered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Кол-во упоминаний')),
            ],
            options={
                'db_table': 'skills_filtered',
            },
        ),
        migrations.CreateModel(
            name='Year_filtered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=64, verbose_name='Год')),
                ('average_salary', models.FloatField(verbose_name='Средняя зарплата')),
                ('count', models.FloatField(verbose_name='Кол-во вакансий')),
            ],
            options={
                'db_table': 'years_filtered',
            },
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='proportion',
            new_name='count',
        ),
    ]
