# Generated by Django 5.1.4 on 2025-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_city_filtered_skill_filtered_year_filtered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('key_skills', models.CharField(blank=True, max_length=512, null=True, verbose_name='Ключевые навыки')),
                ('salary_from', models.FloatField(verbose_name='Зарплата от')),
                ('salary_to', models.FloatField(verbose_name='Зарплата до')),
                ('salary_average', models.FloatField(verbose_name='Средняя зарплата')),
                ('salary_currency', models.CharField(blank=True, max_length=64, null=True, verbose_name='Валюта')),
                ('area_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Местоположение')),
                ('published_at', models.DateTimeField(null=True, verbose_name='Время публикации')),
                ('date', models.IntegerField(null=True, verbose_name='Год публикации')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
