# Generated by Django 5.1.4 on 2025-01-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_vacancy_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Навык')),
                ('count', models.IntegerField(verbose_name='Кол-во упоминаний')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
