# Generated by Django 5.1.4 on 2025-01-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
