# Generated by Django 5.1.4 on 2025-01-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_filtered',
        ),
        migrations.DeleteModel(
            name='Skill_filtered',
        ),
        migrations.DeleteModel(
            name='Year_filtered',
        ),
    ]
